### ISSUE TITLE
[Airbrake] [Production] Authorization failed.  Server message: {  "error": "unauthorized_client",  "error_description": "Client is unauthorized to retrieve access tokens using this method." }

### ISSUE THREAD

**Issue by yasyf** [yasyf/vc#133]
**Airbrake error:** [#0653](https://herokuapp51418729herokucom.airbrake.io/projects/129829/groups/1876433134257590653)
**Airbrake project:** drfvote

**Error type:** `Signet::AuthorizationError`
**Error message:** `` Authorization failed.  Server message: {  "error": "unauthorized_client",  "error_description": "Client is unauthorized to retrieve access tokens using this method." } ``
**Where:** `rake#sync:trello`
**Occurred at:** Feb 01, 2017 23:37:39 UTC
**First seen at:** Feb 01, 2017 23:37:39 UTC
**Occurrences:** 0 (0 since last deploy on Feb 01, 2017 23:22:13 UTC)

**URL:** `<no information>`
**File:** `[GEM_ROOT]/gems/signet-0.7.3/lib/signet/oauth_2/client.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/signet-0.7.3/lib/signet/oauth_2/client.rb:981:in fetch_access_token
[GEM_ROOT]/gems/signet-0.7.3/lib/signet/oauth_2/client.rb:998:in fetch_access_token!
[GEM_ROOT]/gems/googleauth-0.5.1/lib/googleauth/signet.rb:69:in fetch_access_token!
[GEM_ROOT]/gems/googleauth-0.5.1/lib/googleauth/signet.rb:45:in apply!
```

**Comment by Andy1125** [comment]
Hi @yasyf How do you solved this issues?
