### ISSUE TITLE
Ignore company information request if recently posted

### ISSUE THREAD

**Issue by wgreendrf** [yasyf/vc#66]
DRFBot will post the company information for "DRF Company" every time the name of "DRF Company" is mentioned in a chat.

If the DRFBot has posted something about "DRF Company" within 5 items in the chat it should ignore the call to avoid noise in the chat channel.

**Comment by yasyf** [comment]
This logic exists already but looks like the threshold needs to be tweaked. Right now it doesn't do it if it did it for that company within the last hour, but message count is probably better.

**Comment by yasyf** [comment]
This should be fixed now.
